["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/main.cairo",
]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]


["profile.testnet2.protostar.deploy"]
gateway-url="http://127.0.0.1:5050/"