[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
main = [
    "src/main.cairo",
]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]


["profile.testnet2.protostar.deploy"]
gateway-url="http://127.0.0.1:5050/"